/*
 * ENCODER PINS
 */
#define ENCODER_1_CHANNEL_NUM 1
#define ENCODER_1_CHANNEL_A 0
#define ENCODER_1_CHANNEL_B 1

#define ENCODER_2_CHANNEL_NUM 2
#define ENCODER_2_CHANNEL_A 3
#define ENCODER_2_CHANNEL_B 4

#define ENCODER_3_CHANNEL_NUM 3
#define ENCODER_3_CHANNEL_A 7
#define ENCODER_3_CHANNEL_B 8

#define ENCODER_4_CHANNEL_NUM 4
#define ENCODER_4_CHANNEL_A 30
#define ENCODER_5_CHANNEL_B 31

/*
 * MOTOR PINS
 */
#define MOTOR_1_PWM_A 29
#define MOTOR_1_PWM_B 28
#define MOTOR_1_SLP 38

#define MOTOR_2_PWM_A 25
#define MOTOR_2_PWM_B 24
#define MOTOR_2_SLP 40

#define MOTOR_3_PWM_A 22
#define MOTOR_3_PWM_B 23

#define MOTOR_4_PWM_A 9
#define MOTOR_4_PWM_B 6